### ISSUE TITLE
Add export feature

### ISSUE THREAD

**Issue by marcj303** [playasoft/grants#72]
Add an export for the application and scores views to be imported to a spreadsheet. This is helpful for scoring meetings as well as individual notes etc.

**Comment by itsrachelfish** [comment]
@Meleeman01 - @marcj303 Gave me copies of the manual exports that were used in previous years. Some of the data in these exports is based on dynamically generated questions so it's going to be necessary to create a migration which adds a new column to the questions table for marking certain questions as being included in exports.

**Basic application data which is already available**
- Project name
- Total score
- Objective score
- Subjective score
- Applicant (username + link to user profile)
- Budget

**Dynamic question fields**
- Minimum funding
- Art location
- Multi-year

**Empty fields for judges**
- Notes 
- Vote to fund 
- Amount funded

The empty fields for judges won't include any data, they are just created as placeholders for judges to fill in during their meetings.

**Comment by itsrachelfish** [comment]
Finished a while back thanks to @Meleeman01
